### ISSUE TITLE
Add logging when PR comment fails to be written in Azure DevOps

### ISSUE THREAD

**Issue by sondr3** [pulumi/pulumi-az-pipelines-task#135]
**Describe the bug**
We're setting up our CI in Azure Pipelines for Pulumi and have gotten it to work, however we have been unable to get it to create comments in the PRs where we change Pulumi code. The CI successfully completes but doesn't create a comment.

**To Reproduce**
```yaml
- task: Pulumi@1
  inputs:
    azureSubscription: ${{ parameters.azureSubscription }}
    command: preview
    cwd: .pulumi
    loginArgs: $(PULUMI_BACKEND_URL)
    stack: ${{ parameters.stack }}
    createPrComment: true
  env:
    BUILD_ID: $(Build.BuildId)
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    AZURE_STORAGE_ACCOUNT: $(AZURE_STORAGE_ACCOUNT)
    AZURE_STORAGE_KEY: $(AZURE_STORAGE_KEY)
    PULUMI_BACKEND_URL: $(PULUMI_BACKEND_URL)
```

**Expected behavior**
A comment appearing in the relevant PR.

**Additional context**
We have configured all relevant authorizations in the Users settings in Azure Devops.
