### ISSUE TITLE
Make a copy-paste ready example yml from the Azure Pipelines example

### ISSUE THREAD

**Issue by StefH** [pulumi/pulumi-az-pipelines-task#41]
Can you please release a copy-paste ready example `yml` for the screenshot which is described on the info page? This makes it easier as a start template.

> Here's how a typical Azure Pipelines build configuration file in YAML looks like using the Pulumi task.
![image](https://user-images.githubusercontent.com/249938/77845053-09be4700-71ac-11ea-8b6e-2a1556d9c9d7.png)

**Comment by leezen** [comment]
While not quite the same, there are a couple examples available in https://github.com/pulumi/pulumi-az-pipelines-task/tree/master/examples -- are those helpful for you to get going?

**Comment by StefH** [comment]
@leeze Thanks, I found this one, but it's very minimal.

Currently I trying to do a `Publish` (from an Azure Fucntion) and a Pulumi Preview, however I'm stuck on the location from the published files.

Azure Pipelines looks like this:
``` yaml
pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  buildProjectFunctions: '**/FunctionsAppV3.csproj'
  tag: '1.0.0'
  buildNumber: $(Build.BuildNumber)

stages:
- stage: publish_and_deploy
  jobs: 
  - job: publish
    displayName: 'Publish'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest')) # Do not run for PullRequests
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: publish
        projects: |
         $(buildProjectFunctions)
        publishWebProjects: false
        arguments: '--configuration $(BuildConfiguration) /p:Version=1.0.0-$(BuildNumber) --output publish'
        zipAfterPublish: false

  - job: deploy
    displayName: 'Deploy via Pulumi'
    dependsOn: publish
    steps:
    - task: pulumi.build-and-release-task.custom-build-release-task.Pulumi@1
      displayName: 'Run pulumi - preview'
      inputs:
        azureSubscription: 'Service Connection for Pulumi'
        command: preview
        cwd: "Pulumi"
        stack: "StefH/azure-function-v3-linux/dev"
      env:
        PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
```

Which publishes the files into `/home/vsts/work/1/s/publish/FunctionsAppV3/`

And my Pulumi Stack looks like this (excerpt):
``` c#
var blob = new Blob("azure-function-zip", new BlobArgs
{
  StorageAccountName = storageAccount.Name,
  StorageContainerName = container.Name,
  Type = "Block",
  Source = new FileArchive(Path.Combine("../", "publish", "FunctionsAppV3"))
});
```

But this fails with:

> pulumi:pulumi:Stack azure-function-v3-linux-dev running error: Running program '/home/vsts/work/1/s/Pulumi/bin/Debug/netcoreapp3.1/Pulumi.Azure.Function.dll' failed with an unhandled exception:
>     pulumi:pulumi:Stack azure-function-v3-linux-dev  1 error
>  
> Diagnostics:
>   pulumi:pulumi:Stack (azure-function-v3-linux-dev):
>     error: Running program '/home/vsts/work/1/s/Pulumi/bin/Debug/netcoreapp3.1/Pulumi.Azure.Function.dll' failed with an unhandled exception:
>     Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="failed to compute archive hash: couldn't read archive path '../publish/FunctionsAppV3': stat ../publish/FunctionsAppV3: no such file or directory")
    
Can you help?
