### ISSUE TITLE
Support for secrets provider

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi-az-pipelines-task#43]
**Is your feature request related to a problem? Please describe.**
I cannot use the task as I cannot set the secrets provider, this forces me to fall back to installing and using Pulumi manually in an Azure CLI task

**Describe the solution you'd like**
Support for --secrets-provider built in the task

**Describe alternatives you've considered**
I tried putting the argument in the args, loginArgs, stack parameters, but none of them work.

**Additional context**
Thank you

**Comment by praneetloke** [comment]
@UnoSD thank you for submitting the issue. I have a few clarifying questions if you could answer them please?

> I cannot use the task as I cannot set the secrets provider

What exactly did not work with the current task? Which secrets provider did you try to use? Lastly, what was the exact input you passed to the `args` property in the task?

**Comment by UnoSD** [comment]
I don't have the task definition anymore as I dropped it in favour of and Azure CLI task but I will try and edit one from the Pulumi example:

  - task: Pulumi@1
    condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
    inputs:
      azureSubscription: "My Service Connection"
      command: preview
      cwd: "infra/"
      stack: "example"

this selects the stack "example" as in:

pulumi stack select dev

but what I need to achieve is:

pulumi stack select dev --secrets-provider="azurekeyvault://$KEYVAULT/keys/pulumi"

And there seems to be no way of doing it currently. I also tried adding the argument to the "stack: ..." in YAML, but it did not work.

**Comment by praneetloke** [comment]
@UnoSD the task has an input param called `args`. You should be able to pass `--secrets-provider="azurekeyvault://$KEYVAULT/keys/pulumi"` to it, as well as any other flag that the command accepts. For example,

```yaml
task: Pulumi@1
condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
inputs:
azureSubscription: "My Service Connection"
command: preview
cwd: "infra/"
stack: "example"
# Not sure about the formatting of quotes here, but try to wrap the whole thing in a single-quote.
args: '--secrets-provider="azurekeyvault://$KEYVAULT/keys/pulumi"'
```

However, the value of `args` is not passed to the `stack select` command that this task runs, and it is in fact not needed, _unless_ you are also trying to create a new stack, which is the only time the `--secrets-provider` flag seems to be [used](https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/stack_select.go#L76) as part of the `stack select` command? If you are trying to create a new stack with a secrets provider, that could be the issue here. So are you using an existing stack or trying to create a new one as part of the task execution automatically?

**Comment by UnoSD** [comment]
I am trying to create a new one as part of the pipeline, unfortunately.

I also tried creating it in a separate task but I recall having the same problem using init.

**Comment by fraPace** [comment]
Hello @praneetloke, 
I am also experiencing the same problem in the stack init when using a secret provider.
I have tried to use the stack command in the task, but since the stack select (and stack init) always run before the actual task command, there is no way to achieve that.
I would be nice to have something like the loginArgs for the stack select (or init).

**Comment by danponting** [comment]
A workaround that I have found to still use the Pulumi task & set a key vault as the secrets provider is the following:

```
    - task: Pulumi@1
      env: PULUMI_CONFIG_PASSPHRASE: //Left empty on purpose
      inputs:
        azureSubscription: "ExampleServiceConnection"
        cwd: "exampleworkingdirectory"
        command: stack
        createStack: true
        stack: "ExampleStack"
        loginArgs: "ExampleArgs"
        args: >
          change-secrets-provider azurekeyvault://examplekeyvault.vault.azure.net/keys/PulumiKey
```
Because the `createStack` property is used, this is acted like a pre step and will happen before the stack is selected. This will create the stack with a standard empty passphrase and there doesnt seem to be a way of overriding this. But then using the `change-secrets-provider` argument forces the stack to update to use the key vault secrets provider.

Its not ideal as the stack is initially created using a passphrase, but then it updated to use the secrets provider, so is inifficient, but is at least a working workaround for using the Pulumi task & using a key vault secrets provider.
