### ISSUE TITLE
`createStack:true` doesn't work when used with  fully qualified stack names

### ISSUE THREAD

**Issue by asizikov** [pulumi/pulumi-az-pipelines-task#53]
**Describe the bug**

`createStack:true` should create a new stack when it doesn't exist, however it doesn't work when I use a fully qualified stack name.

**To Reproduce**

1. Create an Azure Pipiline with a task like this:
```yaml
                - task: Pulumi@1
                  displayName: 'Create new Stack if needed'
                  inputs:
                    azureSubscription: $(azureSubscriptionName)
                    command: 'stack'
                    args: 'select $(stackName)'
                    cwd: 'infra/'
                    stack: '$(stackName)'
                    createStack: true
```
2. Run the pipeline

When the `$stackName` variable contains the short name for the stack it works ok, however when I use a fully qualified name `organization/project/stack-name` my pipeline failes.

In logs I can see 

```bash
pulumi stack select my-org-redacted/infra/does-not-exist
error: no stack named 'does-not-exist' found
```

**Expected behavior**

A new stack should be created

**Screenshots**

**Additional context**

This feature was introduced in https://github.com/pulumi/pulumi-az-pipelines-task/pull/36  

In particular this line:
https://github.com/pulumi/pulumi-az-pipelines-task/blob/db5d6c9dc6c42da75eb27fd3a91267f91b9b4f38/buildAndReleaseTask/pulumi.ts#L50

```ts
const errMsg = `no stack named '${pulStack}' found`;
```

I believe the the comparison is made with the full name, but the actual error message contains a short name. Hence there is no match and the pipeline fails.
