### ISSUE TITLE
A better way to install plugins

### ISSUE THREAD

**Issue by darnmason** [pulumi/pulumi-az-pipelines-task#61]
I use a build pipeline to publish an artifact of my Pulumi project and another pipeline downloads that artifact to execute it.

This means that I have Pulumi configured with the binary option:
```yaml
name: project-name
runtime:
  name: dotnet
  options:
    binary: Project.Name.dll
description: Blah
```

I discovered that this means Pulumi can't/won't install plugins used by the binary. So now I've resorted to the following steps when executing Pulumi:

```yaml
- task: Pulumi@1
  displayName: 'Install Azure-Native'
  inputs:
    azureSubscription: '$(azureSubscription)'
    command: plugin
    args: 'install resource azure-native v0.7.1'
    cwd: '$(workingDir)'
    stack: '$(pulumiStack)'
    createStack: true
- task: Pulumi@1
  displayName: 'Install Random'
  inputs:
    azureSubscription: '$(azureSubscription)'
    command: plugin
    args: 'install resource random v3.1.0'
    cwd: '$(workingDir)'
    stack: '$(pulumiStack)'
    createStack: true
- task: Pulumi@1
  displayName: 'Pulumi up'
  inputs:
    azureSubscription: '$(azureSubscription)'
    command: up
    args: '--yes'
    cwd: '$(workingDir)'
    stack: '$(pulumiStack)'
    createStack: true
```

Is there a better way to do this or can I request one?

**Comment by praneetloke** [comment]
@darnmason `pulumi` not installing the plugins automatically when you use the `binary` option is expected since the Pulumi CLI doesn't support it when you use the `binary` option. Another related issue is https://github.com/pulumi/pulumi/issues/5334 (and specifically this [comment](https://github.com/pulumi/pulumi/issues/5334#issuecomment-704230763)). cc @mikhailshilkov just in case he is aware of anymore options for .NET binaries specifically. My ideal solution would be for the CLI would be to emit a manifest file of sorts for language runtimes that support pre-built binaries, so that users could use that manifest to tell the CLI to install plugins from that with a single command, or better yet detect the presence of the manifest file in the current folder and automatically install from that.

The current workaround that I myself use sometimes is to add a [`CmdLine`](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml) task step after the Pulumi CLI has been installed by a previous Pulumi task step. (I have long wanted to allow adding the Pulumi task without requiring a command to be selected so that the task would simply install the CLI and bail because no command was provided. Today you have to specify a command.) Once the CLI is install, I then add all the `pulumi plugin install ...` commands in the single `CmdLine` task step as a multi-line script statement. It's not ideal but it is better than having to repeat the `Pulumi` task step for every plugin you need to install.

And for a better way to install the plugins for pre-built binaries, would it be helpful if the task supported a special "custom" command, where you could simply enter all the `pulumi plugin install ...` commands into the task itself and let it run those after installing the CLI? I would love to hear if you have any other thoughts on this as well.

**Comment by praneetloke** [comment]
@darnmason since v1.0.9 you should be able to use the task extension to simply install the CLI and then run a single `script` task to install all plugins. It's still not the best experience but slightly better than having to specify the Pulumi task multiple times for each plugin you want to install.

```yaml
- task: Pulumi@1
   displayName: Install Pulumi CLI
- script: |
     pulumi plugin install resource azure-native v0.7.1
     pulumi plugin install resource random v3.1.0
     ...
     ...
- task: Pulumi@1
   input:
     cmd: up
     args: --yes
     stack: mystack
```

(Note to other readers: you are only need to install the plugins manually if you are using a pre-built binary with Pulumi at this time.)
