### ISSUE TITLE
Pulumi extension task fails when ran as part of a deployment

### ISSUE THREAD

**Issue by tap1992** [pulumi/pulumi-az-pipelines-task#91]
**Describe the bug**

Using the Pulumi Azure DevOps extension's task within a deployment job it fails with the below error. If i copy and paste the same task into a normal job it works perfectly fine.

##[error]Error: There was an error when attempting to execute the process '/__w/_temp/c0162cb7-b00c-44f7-a09c-82bb8eefcc6a/pulumi/pulumi'. This may indicate the process failed to start. Error: spawn /__w/_temp/c0162cb7-b00c-44f7-a09c-82bb8eefcc6a/pulumi/pulumi ENOENT

**To Reproduce**

Using YAML pipelines, use a normal job with steps and utilise the pulumi task as shown below:
jobs:
-  job: test
   steps:
      - task: Pulumi@1
        inputs:
          azureSubscription: ***
          command: 'preview'
          cwd: '***'
          stack: '***'
          args: '--diff'
          loginArgs: azblob://***

It should work as normal.
If we use the deployment version of a job as per below it will fail:

  - deployment: deploy_job
    environment: ***
    workspace:
      clean: all
    strategy: 
      runOnce:
        deploy:
          steps:
            - task: Pulumi@1
              inputs:
                azureSubscription: ***
                command: 'preview'
                cwd: '***'
                stack: '***'
                args: '--diff'
                loginArgs: azblob://***

**Expected behavior**

Pulumi preview should run and generate the output in logs.

**Screenshots**

**Additional context**

**Comment by praneetloke** [comment]
It seems that you will need to include a step to checkout the source code in your deployment job since they do not automatically clone the source repo. See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops.

> A deployment job doesn't automatically clone the source repo. You can checkout the source repo within your job with `checkout: self`. Deployment jobs only support one checkout step.

```yaml
deploy:
  steps:
    # Add this step before running Pulumi.
    - checkout: self

    - task: Pulumi@1
      inputs:
        azureSubscription: ***
        command: 'preview'
        cwd: ''
        stack: ''
        args: '--diff'
        loginArgs: azblob://***
```
